config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"}
  
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  put '/admin/users/:user_id/permissions',
      :to => 'admin/permissions#update',
      :as => :update_user_permissions
    
  root :to => "projects#index"
  
  resources :projects do
    resources :tickets
  end
  
  default_url_options :host => "example.com"
  
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
     <%= yield(:title) %>
   <% else %>
    Ticketee
   <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



</body>

<body>

	<div id="contenido"> 

		<div id="header"> <img src="/images/header.jpg" alt="" /> </div>
		<div id="main">
			<div id="info"> 
                                <% flash.each do |key, value| %>
                                  <div class='flash' id='<%= key %>'>
                                    <%= value %>
                                  </div>
                                <% end %>

                                <%= link_to image_tag('/images/title.jpg'), root_path %> 
                                <%= yield %>
                                
                                <nav>
                                  <% if user_signed_in? %>
                                    Signed in as <%= current_user.email %>
                                    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                                  <% else %>
                                    <%= link_to "Sign in", new_user_session_path %> | 
                                    <%= link_to "Sign up", new_user_registration_path %>
                                  <% end %>
                                  <%= admins_only do %>
                                    <%= link_to "Admin", admin_root_path %><br>
                                  <% end %>
                                </nav>  
                        </div>

		</div>
	
	</div>

</body>
</html>